version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.apis:google-api-services-youtube
    versions:
    - v3-rev20201214-1.31.0
    - v3-rev20210210-1.31.0
    - v3-rev20210407-1.31.0
  - dependency-name: io.reactivex.rxjava3:rxjava
    versions:
    - 3.0.10
    - 3.0.11
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
    - 4.1.3
  - dependency-name: com.android.tools:desugar_jdk_libs
    versions:
    - 1.1.5
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
  - dependency-name: com.google.android.exoplayer:exoplayer-core
    versions:
    - 2.13.0
    - 2.13.2
  - dependency-name: com.google.android.exoplayer:exoplayer-ui
    versions:
    - 2.13.0
    - 2.13.2
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: com.squareup.leakcanary:leakcanary-android
    versions:
    - "2.6"
