name: Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'
        required: true
        default: 'v2.988'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: "adopt"
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: ./gradlew assembleRelease
